name: Clean pool
on:
  workflow_call:
    inputs:
      pool-tag:
        required: true
        type: string
    secrets:
      DEVHUB_SFDX_AUTH_URL:
        required: true

jobs:

  clean-pool:
    name: 'Clean ${{ inputs.pool-tag }} pool'
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts

    steps:
      - uses: actions/checkout@v2

      - name: 'Authenticate Dev Hub'
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub

      - name: 'Drop the pool'
        run: 'sfdx sfpowerscripts:pool:delete -t dev -v devhub'