name: Docker Build and Publish

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}/${{ inputs.image }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: dockerfiles
          file: dockerfiles/${{ inputs.image }}.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ inputs.image }}:${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}