name: Prepare pool
on:
  workflow_call:
    inputs:
      pool-tag:
        required: true
        type: string
      git-ref:
        description: "Commit Id from where the pools should be created"
        required: false
        default: 'main'
        type: string
      datadog:
        required: false
        type: boolean
        default: false
      newrelic:
        required: false
        type: boolean
        default: false
    secrets:
      DEVHUB_SFDX_AUTH_URL:
        required: true
      DATADOG_HOST:
        required: false
      DATADOG_API_KEY:
        required: false
      NEWRELIC_INSIGHT_INSERT_KEYS:
        required: false
          
env:
  SFPOWERSCRIPTS_NEWRELIC: "${{ inputs.newrelic }}"
  SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}'
  SFPOWERSCRIPTS_DATADOG: "${{ inputs.datadog }}"
  SFPOWERSCRIPTS_DATADOG_HOST: "${{ secrets.DATADOG_HOST }}"
  SFPOWERSCRIPTS_DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"

jobs:
  pool:
    name: 'Replenish "${{ inputs.pool-tag }}" pool'
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    timeout-minutes: 720 #Set to Maximum Time out
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: ${{ inputs.git-ref }}
          fetch-depth: 0

    
      - name: 'Authenticate Dev Hub'
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub

      # Authenticate to npm
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: 'Prepare a pool of scratch orgs'
        run: 'sfdx sfpowerscripts:orchestrator:prepare -f config/project-${{ inputs.pool-tag }}-pool-def.json -v devhub'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      # Publish artifacts
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: scratchorg-logs-pool-${{ inputs.pool-tag }}
          path: .sfpowerscripts/prepare_logs