name: SFDX Image Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'dockerfiles/**'
    tags:
      - '*'
  workflow_dispatch:


jobs:
  build-publish:
    uses: ./.github/workflows/docker-build-publish.yml
    strategy:
      matrix: 
        image: [sfdx-slim, sfdx-alpine]
    with:
      image: ${{ matrix.image }}
    permissions:
      packages: write
      contents: read